language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE rechargeables_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: iCuQFdrl5aayRN6ZZ+U5YjXNbHkDXs5/BaE+NowyYkJeL6Vv/T9l7uebom0x4y66eQtx6KktDGeyxANzOqKHyCBz2lYZsF6+mkomCsG6u2onnJGoNJ1agigJD4PuAINbENv3hX1Dt+nmfUk0Agxnza+CE3bNAijDAOxyUf+fnXWo39oinBt1JK4Ds8XjfCGfPuYMKof0/MS8+ZoL0/fcKjWhORLgEp361tzjOCTYy9zNDipPelBrvwHG/FVh0OGN0lIze56+mV3g7vMvdhQk/L5a+bhrG6z8DuFMcyq33L7tYbN1YrxJKLEMLvDw26DRFL3n202FaACttrDWXTrksEOVT+5kUQAJ6QBU3xpPuo26GmSDT4pKNDmX/oX1D1bRZ9aQXvmJAU6kpuzA0B1qTIxz8P9FhGcHj7tJHVyfBE691Zatx9fVrQceVX9XYiCJ1tjV9LQwlmwOCFbkvyrGjo88y3+y4qsFZ8GHgI6Vu5LVi7bn3tWaD3Mdlgamljni6s+TVvjiyoSYQ2rwqQD86l8j6MT5b1WN8vNJYKRnzDUHJq/qGvty+ZJcIYNrjy3tb2WflsTpAgzEQx18wWhb180UPtSb3tFZj2v9WXa/VhsvYG16lBnG7wZWJgQi428hvfnnSsiVFBJsJPJfaVaoAW9zsO5CniYS03ODY7qnmww=
  app: recharge-api
  skip_cleanup: true